[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
capstone = "DE4KPDfn9VzefyW9tD1otBGDymbGMxHstXkcKWnpjRKB"

[programs.localnet]
capstone = "DE4KPDfn9VzefyW9tD1otBGDymbGMxHstXkcKWnpjRKB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = 'C:\Users\Awesome_webber/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
