[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
capstone = "5PEiejjMZfsefWvV63HYD8Nry52bY3r6N3cWigccxs7m"

[programs.localnet]
capstone = "5PEiejjMZfsefWvV63HYD8Nry52bY3r6N3cWigccxs7m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
